
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 01 21:52:23 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 25;
  public static final int CONST = 35;
  public static final int GEQUAL = 34;
  public static final int NOTEQUAL = 32;
  public static final int LPAREN = 13;
  public static final int GREATER = 33;
  public static final int SEMI = 5;
  public static final int CONTINUE = 18;
  public static final int LESS = 36;
  public static final int FOR = 16;
  public static final int MINUS = 29;
  public static final int DECREMENT = 26;
  public static final int STATIC = 15;
  public static final int RPAREN = 14;
  public static final int AND = 28;
  public static final int OR = 27;
  public static final int COMMA = 6;
  public static final int CLASS = 10;
  public static final int DIVEQUAL = 45;
  public static final int DIV = 42;
  public static final int PLUS = 38;
  public static final int IF = 22;
  public static final int DOT = 30;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int EQUAL = 7;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int ISEQUAL = 31;
  public static final int MUL = 41;
  public static final int NUMBER = 47;
  public static final int MOD = 43;
  public static final int PLUSEQUAL = 39;
  public static final int IDENT = 48;
  public static final int BREAK = 17;
  public static final int VOID = 12;
  public static final int LBRACE = 3;
  public static final int ELSE = 21;
  public static final int LSQUARE = 8;
  public static final int LEQUAL = 37;
  public static final int READ = 24;
  public static final int CHARCONST = 50;
  public static final int MINUSEQUAL = 40;
  public static final int RSQUARE = 9;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 49;
  public static final int EXTENDS = 11;
  public static final int PROG = 2;
  public static final int MODEQUAL = 46;
  public static final int MULEQUAL = 44;
  public static final int PRINT = 20;
}

